### ISSUE TITLE
Connection failed even after changing the fingerprint 

### ISSUE THREAD

**Issue by smolbun** [SensorsIot/HTTPS-for-Makers#2]
I've tried  /ESP8266/HTTPSRequest and HTTPSRequestHowMySSL both returned "Connection failed" and there was no further reply after that. I've changed the fingerprint but still stuck with the same probelm

**Comment by Grand-Max** [comment]
> 
> 
> I've tried /ESP8266/HTTPSRequest and HTTPSRequestHowMySSL both returned "Connection failed" and there was no further reply after that. I've changed the fingerprint but still stuck with the same probelm

Hey!I am facing the same problem, how did you solve it?
